project:
  type: book

book:
  title: "Random Notes on Pragmatic Optimization"
  author: "Kunlei Lian"
  date: "8/15/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



